on: [push]

name: CI

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
